### ISSUE TITLE
latest Papi version is 0.3, this tag is missing here.

### ISSUE THREAD

**Issue by onkelbeh** [exxamalte/python-georss-qld-bushfire-alert-client#1]
latest Papi version is 0.3, this tag is missing here:
<img width="726" alt="Bildschirmfoto 2020-09-08 um 18 37 51" src="https://user-images.githubusercontent.com/42828703/92504113-7bda9380-f202-11ea-8710-a568b93cdb3d.png">

**Comment by exxamalte** [comment]
Sorry, I must have missed that. Just added tag v0.3.

**Comment by onkelbeh** [comment]
Thanks, and sorry for the Typo :-)
