### ISSUE TITLE
XML URL appears to have been changed.

### ISSUE THREAD

**Issue by pheven42069** [exxamalte/python-georss-qld-bushfire-alert-client#29]
The URL specified in feed.py ("https://www.qfes.qld.gov.au/data/alerts/bushfireAlert.xml") doesn't appear to be valid currently.

The Current bushfire warnings and incidents page on the Queensland Fire Department's website presently links to an XML file located at "https://publiccontent-gis-psba-qld-gov-au.s3.amazonaws.com/content/Feeds/BushfireCurrentIncidents/bushfireAlert.xml".

I've swapped the URL over in my feed.py file and everything seems to work no wukkas, not sure why they changed the location or if they'll change it back though.

**Comment by exxamalte** [comment]
Thanks for reporting this. I'll change the URL in the library asap.

**Comment by pheven42069** [comment]
Cheers exxamalte, really appreciate your work.
